
import os
import sys
import json
import feedparser
import requests
import re

from bs4 import BeautifulSoup
from src.generators.llm import _summarize_with_grok, _summarize_with_gemini

# --- Utility: Text Cleaner ---
def clean_html(text):
    if not text: return ""
    return re.sub(r'<[^>]+>', '', text).strip()

# --- 1. Naver Summarizer ---
def _summarize_with_naver(title, content):
    client_id = os.getenv("NAVER_CLIENT_ID")
    client_secret = os.getenv("NAVER_CLIENT_SECRET")
    
    if not client_id or not client_secret:
        return "[Naver] API Key Missing"

    url = "https://naveropenapi.apigw.ntruss.com/text-summary/v1/summarize"
    headers = {
        "X-NCP-APIGW-API-KEY-ID": client_id,
        "X-NCP-APIGW-API-KEY": client_secret,
        "Content-Type": "application/json"
    }
    
    # Naver Limit: 2000 chars total
    full_text = f"{title}. {content}"
    if len(full_text) > 1800:
        full_text = full_text[:1800]
        
    data = {
        "document": {
            "title": title[:300], # safe buffer
            "content": full_text
        },
        "option": {
            "language": "ko",
            "model": "news",
            "tone": 2, # Polite
            "summaryCount": 3
        }
    }
    
    try:
        resp = requests.post(url, headers=headers, json=data)
        if resp.status_code == 200:
            return resp.json().get('summary', 'No summary')
        else:
            return f"[Naver] Error {resp.status_code}: {resp.text}"
    except Exception as e:
        return f"[Naver] Exception: {e}"

# --- 2. Wrappers for consistency ---
def summarize_all(title, content, link):
    results = {}
    
    # Common prompt for LLMs (Simplified for comparison)
    prompt = f"""
    다음 뉴스 기사를 한국어로 3줄 요약해줘.
    제목: {title}
    내용: {content[:3000]}
    URL: {link}
    """
    
    # 1. Grok
    try:
        results['Grok'] = _summarize_with_grok(prompt)
    except Exception as e:
        results['Grok'] = f"Error: {e}"

    # 2. Gemini
    try:
        with open(".env", "r") as f:
            for line in f:
                if line.startswith("GEMINI_API_KEY="):
                    os.environ["GEMINI_API_KEY"] = line.strip().split("=", 1)[1]
        results['Gemini'] = _summarize_with_gemini(prompt)
    except Exception as e:
        results['Gemini'] = f"Error: {e}"

    # 3. Naver
    results['Naver'] = _summarize_with_naver(title, clean_html(content))
    
    return results

# --- 3. Main Logic ---
def main():
    # Load ENV manually if needed, or rely on existing mechanism
    # Assuming config.py style loading isn't fully available in standalone script 
    # without path hacks, so loading basic keys here.
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except:
        pass

    # Targets: 4 AI, 4 XR
    targets = {
        "AI": "docs/ai/daily/2025-12-14_074552.html",
        "XR": "docs/xr/daily/2025-12-14_074552.html"
    }
    
    output_md = "# Model Comparison: Grok vs Gemini vs Naver\n\n"
    
    for category, path in targets.items():
        if not os.path.exists(path):
            print(f"File not found: {path} - Trying generic recursive find...")
            # Fallback logic if date changed
            continue
            
        with open(path, "r", encoding="utf-8") as f:
            soup = BeautifulSoup(f, "html.parser")
            
        articles = soup.select("article.news-item")[:4]
        
        output_md += f"## {category} Articles ({len(articles)})\n\n"
        
        for i, art in enumerate(articles):
            title = art.select_one(".news-title a").get_text(strip=True)
            link = art.select_one(".news-title a")['href']
            # Re-fetch content to get full text? 
            # Actually, the HTML only has summary. 
            # To do a fair comparison, we need ORIGINAL content or at least the snippet.
            # But user wants summary OF THE ARTICLES. 
            # Using the snippet inside HTML is unfair to Naver/LLMs if it's already summarized.
            # However, fetching real content is slow/complex (scraping).
            # I will try to fetch the RSS feed or use the text in HTML if it's long enough.
            # Wait, the HTML *only* contains the summary generated by Grok previously.
            # Re-summarizing a summary is bad.
            # I must fetch the URL content.
            
            print(f"Fetching original content for: {title}")
            try:
                # Simple scrape attempt
                r = requests.get(link, timeout=10, headers={"User-Agent": "Mozilla/5.0"})
                # Minimal generic extraction
                # Just get all p tags
                page_soup = BeautifulSoup(r.text, "html.parser")
                paragraphs = page_soup.select("p")
                content = "\n".join([p.get_text() for p in paragraphs])
                # Filter short garbage
                content = content[:4000] 
            except Exception as e:
                content = f"Failed to fetch original content: {e}. Using title only."
            
            output_md += f"### {i+1}. {title}\n"
            output_md += f"**URL**: {link}\n\n"
            
            summaries = summarize_all(title, content, link)
            
            output_md += "| Model | Summary |\n|---|---|\n"
            for model, text in summaries.items():
                clean_text = text.replace("\n", "<br>")
                output_md += f"| **{model}** | {clean_text} |\n"
            output_md += "\n---\n"

    print("Comparison complete.")
    with open("comparison_results.md", "w", encoding="utf-8") as f:
        f.write(output_md)

if __name__ == "__main__":
    main()
