name: Daily AI News

on:
  schedule:
    - cron: "0 0 * * *"   # 매일 09:00 KST ≒ 매일 00:00 UTC
  workflow_dispatch:        # 필요할 때 수동 실행 버튼

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate AI News HTML
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python generate_news.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docs/index.html
          git commit -m "Update daily AI news" || echo "No changes"
          git push
